language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  matrix:
    - LODASH="npm install lodash@1.3.0"
    - LODASH="npm install lodash@1.3.1"
git:
  depth: 1
before_install:
  - "npm install -g grunt-cli"
before_script:
  - 'npm remove lodash'
  - $LODASH