language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  global:
    - LODASH
  matrix:
    - "lodash@1.2.0"
    - "lodash@1.2.1"
    - "lodash@1.3.0"
    - "lodash@1.3.1"
before_script:
  - "npm install -g grunt-cli"
  - "npm install $LODASH"