language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  matrix:
    - LODASH_CLI="npm install lodash-cli@1.3.1"
    - LODASH_CLI="npm install lodash-cli@2.0.0"
git:
  depth: 1
branches:
  only:
    - master
before_install:
  - "npm install -g grunt-cli"
  - $LODASH_CLI
