language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  matrix:
    - LODASH="npm install lodash@1.2.0"
    - LODASH="npm install lodash@1.2.1"
    - LODASH="npm install lodash@1.3.0"
    - LODASH="npm install lodash@1.3.1"
before_install:
  - "npm install -g grunt-cli"
  - $LODASH
before_script:
  - 'rm -r node_modules/grunt-lodash/node_modules/lodash'