language: node_js
node_js:
  - "0.8"
  - "0.10"
env:
  matrix:
    - LODASH_VERSION="1.3.1"
    - LODASH_VERSION="2.0.0"
git:
  depth: 1
branches:
  only:
    - master
before_install:
  - "npm i -g grunt-cli"
  - "npm i lodash-cli@$LODASH_VERSION"
