language: node_js
node_js:
  - "0.10"
env:
  matrix:
    - LODASH_CLI="npm install lodash-cli@1.3.0"
    - LODASH_CLI="npm install lodash-cli@1.3.1"
git:
  depth: 1
before_install:
  - "npm install -g grunt-cli"
before_script:
  - 'npm remove lodash-cli'
  - $LODASH_CLI
